### PR TITLE
DS-3837: Fix order in QStatisticsTestingInfo after subsetting complex QTables

### PR DESCRIPTION
**Pull request by mwmclean**
* Also DS-3829: Add lookup indices to QStatisticstestingInfo

### CODE REVIEW

**Comment by jrwishart** [comment]
Getting a weird error that might be of no consequence but should ultimately get fixed.

```
 tbls[[3]] |> str()
Error in names(dimnames.x) <- switch(dim.len, "Row", c("Row", "Column"),
  :
  attempt to set an attribute on NULL
```

**Comment by mwmclean** [comment]
I'll add some code to protect against this. I find the dimnames names helpful and would prefer to add them in the main `[` function if they are missing. Why is the check on `subset-tables.R#L13` not preventing the `str` call from reaching the code that throws the error?

**Comment by jrwishart** [comment]
> I'll add some code to protect against this. I find the dimnames names helpful and would prefer to add them in the main `[` function if they are missing. Why is the check on `subset-tables.R#L13` not preventing the `str` call from reaching the code that throws the error?

which file?

**Comment by jrwishart** [comment]
Did you mean here ? https://github.com/Displayr/verbs/blob/52c8443e2c0fe527a5a00f5fda570195824c3c97/R/subscript-tables.R#L13 (got confused by subset-tables.R with the utils R source code)

**Comment by mwmclean** [comment]
Should be fixed in 08b6ef4d2. Added code to name the `dimnames` if they aren't named and fixed `updateQStatisticsTestingInfo` to not error if the qTable has no `dimnames`.

**Review by jrwishart — APPROVED** [review]

**Pull request merged**
