### PR TITLE
DS-3313 Add Multiply, Divide and Subtract

### PR DESCRIPTION
**Pull request by jrwishart**

### CODE REVIEW

**Review by mwmclean — CHANGES_REQUESTED** [review]
1. Fuzzy matching seems to be occurring if specify `match.elements = "Yes - hide unmatched"` or `match.elements = "Yes - show unmatched"` [vector ex.|https://staff.displayr.com/Dashboard?project_id=-883155#page=56d97128-4303-483c-ad89-680a8586ec5c], [matrix ex.|https://staff.displayr.com/Dashboard?project_id=-883155]
2. Should we add a warning if dividing by 0? `/` does not
3. Is there a reason we default to not warning if the statistics on two input Q tables don't match?
4. Is there a reason to not have a `...` argument to multiply and add support for multiplying more than two elements?

**Comment by jrwishart** [comment]
> 1. Fuzzy matching seems to be occurring if specify `match.elements = "Yes - hide unmatched"` or `match.elements = "Yes - show unmatched"` [vector ex.|https://staff.displayr.com/Dashboard?project_id=-883155#page=56d97128-4303-483c-ad89-680a8586ec5c], [matrix ex.|https://staff.displayr.com/Dashboard?project_id=-883155]
> 2. Should we add a warning if dividing by 0? `/` does not
> 3. Is there a reason we default to not warning if the statistics on two input Q tables don't match?
> 4. Is there a reason to not have a `...` argument to multiply and add support for multiplying more than two elements?

1. The fuzzy matching is due to the single character difference and the Automatic behaviour will choose fuzzy matching if it gives a better count than exact matching.
2. Warnings need to be turned on with the `warn` argument if running custom R code. Added functions to check for division by zero and also the NaN case (0/0).
3. I have changed the code in the last commit to check for multiple stats now. It was turned off before and should now throw warnings.
4. It was decided to only allow two inputs since there isn't any easy way to have multiple inputs for multiply in the interface and also allow multiplying by a scalar. It can be added in for the R code but would require a refactor for Multiply.

**Comment by mwmclean** [comment]
So are you saying that if I specify `match.elements = "Yes - show unmatched"`, I get different behaviour than `match.elements = c(rows = "Yes - show unmatched", columns = "Yes - show unmatched")` and it's actually equivalent to `c(rows = "Fuzzy - show unmatched", columns = "Fuzzy - show unmatched")`?

It seems like there should probably be a minimum amount of characters needed to perform fuzzy matching, perhaps three.

**Comment by jrwishart** [comment]
> So are you saying that if I specify `match.elements = "Yes - show unmatched"`, I get different behaviour than `match.elements = c(rows = "Yes - show unmatched", columns = "Yes - show unmatched")` and it's actually equivalent to `c(rows = "Fuzzy - show unmatched", columns = "Fuzzy - show unmatched")`?

Yes, the former runs the automatic selection algorithm where the row and column matching are chosen to be either exact or fuzzy depending on the match count and possible transpose the right input (where direction is interpreted in the call to `Reduce`). The latter specifies the behaviour precisely.

> It seems like there should probably be a minimum amount of characters needed to perform fuzzy matching, perhaps three.

Sounds like a good sensible recommendation and I can perhaps implement this but anticipate it may break a lot of tests. Could discuss at the stand up about a new JIRA for this? It isn't isolated to Divide, Multiply and Subtract and affects the whole calculation suite.

**Comment by mwmclean** [comment]
That just seems extremely confusing as a user of the R code. What about renaming `match.elements = c(rows = "Yes - show unmatched", columns = "Yes - show unmatched")` to `match.elements = c(rows = "Exact - show unmatched", columns = "Exact - show unmatched")`?

Fine with discussing minimum chars for fuzzy matching tomorrow in stand-up and leaving it out of this PR.

**Comment by jrwishart** [comment]
> That just seems extremely confusing as a user of the R code. What about renaming `match.elements = c(rows = "Yes - show unmatched", columns = "Yes - show unmatched")` to `match.elements = c(rows = "Exact - show unmatched", columns = "Exact - show unmatched")`?
> 
> Fine with discussing minimum chars for fuzzy matching tomorrow in stand-up and leaving it out of this PR.
> 
> Just need to fix up a couple unit tests.

The tests are fine in the dev branch, it seems something strange happens with the merge commit. i.e. the dev branch passes but some lines of code that were removed a while ago are reappearing in the merge commit.

**Comment by jrwishart** [comment]
Think I have it sorted now. I thought my local master was behind only by the most recent commit to master. However my local master branch didnt have the 2nd last commit too which included the statistic name changes I'll fix it.

**Review by mwmclean — APPROVED** [review]

**Pull request merged**
